root: "data/sentinel2"
batch_size: 32
num_workers: 2
patch_size: 64
step: 256
bands:
  - "B01"
  - "B02"
  - "B03"
  - "B04"
  - "B05"
  - "B06"
  - "B07"
  - "B08"
  - "B8A"
  - "B09"
  - "B10"
  - "B11"
  - "B12"
